name = "welshdag-explorer"
type = "javascript"
main = "./.next/server/app.js"
compatibility_date = "2024-12-10"

[env.production]
vars = { BLOCKDAG_RPC_URL = "http://129.121.92.232:18545" }

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.{js,ts,tsx}"]

[build.upload]
format = "service-worker"
